name: AI PR Reviewer (Bedrock Nova - Manual Trigger)

on:
  pull_request:
    types: [opened, synchronize, reopened]   # runs automatically on PR events
  workflow_dispatch:   # allows manual trigger
    inputs:
      pr_number:
        description: 'Pull Request Number to review'
        required: true
        type: string
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      aws_region:
        description: 'AWS Region (default: ap-south-1)'
        required: false
        default: 'us-east-1'
        type: string

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject PR context (manual runs)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "GITHUB_EVENT_NAME=pull_request" >> $GITHUB_ENV
          echo "{\"pull_request\":{\"number\":${{ github.event.inputs.pr_number }}}}" > event.json
          echo "GITHUB_EVENT_PATH=$PWD/event.json" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id || secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key || secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region || 'us-east-1' }}

      - name: Run Bedrock PR Reviewer
        uses: tmokmss/bedrock-pr-reviewer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: true
          review_simple_changes: false
          review_comment_lgtm: false
          bedrock_light_model: amazon.nova-lite-v1:0
          bedrock_heavy_model: amazon.nova-pro-v1:0
