name: AI PR Reviewer (Bedrock Nova - Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      aws_region:
        description: 'AWS Region (e.g. us-east-1)'
        required: false
        default: 'us-east-1'
        type: string

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (manual inputs)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Run Bedrock PR Reviewer
        uses: tmokmss/bedrock-pr-reviewer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          bedrock_light_model: amazon.nova-lite-v1:0
          bedrock_heavy_model: amazon.nova-pro-v1:0
